version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.10
    environment:
      VERSION: 9
    steps:
    - checkout
    - setup_remote_docker
      # prepare qemu
    - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      # build image
    - run: make build VERSION=$VERSION
  push:
    docker:
    - image: circleci/golang:1.10
    environment:
      VERSION: 9
    steps:
    - checkout
    - setup_remote_docker
    - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - run: make docker-push VERSION=$VERSION
workflows:
  version: 2
  build_and_test:
    jobs:
    - build
    - push:
        filters:
          branches:
            only: master